import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { ComponentsProvider } from "../contexts/ComponentsContext";
import Editor from "../components/editor/Editor";
import Sidebar from "../components/Sidebar";
import Header from "../components/Header";
import Inspector from "../components/Inspector";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <ComponentsProvider>
        <Head>
          <title>Nucleus - Playground</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <div className={styles.main}>
          <Sidebar />
          <div className={styles.editorWrapper}>
            <Editor />
          </div>
          <div className={styles.inspectorWrapper}>
            <Inspector />
          </div>
        </div>
      </ComponentsProvider>
    </div>
  );
};

export default Home;
