import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import DraggableComponent from '../components/DraggableComponent'
import { ComponentsProvider } from '../contexts/ComponentsContext'
import Preview from '../components/Preview'
import componentsList from './_componentList';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nucleus - Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ComponentsProvider>
      <main className={styles.main}>
          <div className={styles.menu}>
              { componentsList.map((component, idx) => <DraggableComponent id={component.id} name={component.name} key={idx} />)}
          </div>
          <Preview/>
          <div className={styles.panel}></div>
      </main>
      </ComponentsProvider>

    </div>
  )
}

export default Home
